routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/profile/edit', 'HomeController@profileEdit')->name('profile.edit');
Route::put('/profile/update', 'HomeController@profileUpdate')->name('profile.update');
Route::get('/profile/changepassword', 'HomeController@changePasswordForm')->name('profile.change.password');
Route::post('/profile/changepassword', 'HomeController@changePassword')->name('profile.changepassword');

Route::group(['middleware' => ['auth','role:Admin']], function ()
{
    // Route::get('/roles-permissions', 'RolePermissionController@roles')->name('roles-permissions');
    // Route::get('/role-create', 'RolePermissionController@createRole')->name('role.create');
    // Route::post('/role-store', 'RolePermissionController@storeRole')->name('role.store');
    // Route::get('/role-edit/{id}', 'RolePermissionController@editRole')->name('role.edit');
    // Route::put('/role-update/{id}', 'RolePermissionController@updateRole')->name('role.update');

    // Route::get('/permission-create', 'RolePermissionController@createPermission')->name('permission.create');
    // Route::post('/permission-store', 'RolePermissionController@storePermission')->name('permission.store');
    // Route::get('/permission-edit/{id}', 'RolePermissionController@editPermission')->name('permission.edit');
    // Route::put('/permission-update/{id}', 'RolePermissionController@updatePermission')->name('permission.update');

    Route::resource('assignrole', 'RoleAssign');
    Route::resource('grade', 'GradeController');
    Route::resource('teacher', 'TeacherController');
    Route::resource('student', 'StudentController');

    Route::get('/search/grade', 'GradeController@search');
    Route::get('/search/student', 'StudentController@search');
    // Route::get('attendance', 'AttendanceController@index')->name('attendance.index');

});

Route::group(['middleware' => ['auth','role:Teacher']], function ()
{
    // Route::post('attendance', 'AttendanceController@store')->name('teacher.attendance.store');
    // Route::get('attendance-create/{classid}', 'AttendanceController@createByTeacher')->name('teacher.attendance.create');

    //Assignment manager
    Route::resource('assignment-manager', 'AssignmentController');
    Route::get('assignment-manager/create/{id}', 'AssignmentController@create')->name('assignment-manager.create-assignment');
    Route::post('assignment-manager/create/store/{id}','AssignmentController@store')->name('assignment-manager.store-assignment');
    Route::get('assignment-manager/download/{file}', 'AssignmentController@downloadFile')->name('assignment-manager.download');
    Route::post('assignment-manager/scoring/{id}','AssignmentController@score')->name('assignment-manager.scoring');

    //Virtual Classroom
    Route::post('/home/update-virtual-classroom/{id}','GradeController@updateVirtualClassroom')->name('update-virtual-classroom');
});

Route::group(['middleware' => ['auth','role:Student']], function ()
{
    //Assignment
    Route::get('assignments', 'AssignmentController@student')->name('assignment.student');
    Route::get('assignments/submit/{id}', 'AssignmentController@submit')->name('assignment.submit');
    Route::post('assignments/submit-assignment/{id}', 'AssignmentController@submitAssignment')->name('assignment.submit-assignment');
});

// now for payment system

Route::group(['middleware' => 'auth'], function (){
    Route::get('payment/show/{id}', 'PaymentController@show')->name('payment.show');
});

app/Models/Assignment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    protected $fillable = [
        'grade_id',
        'teacher_id',
        'title',
        'description',
    ];

    public function grade()
    {
        return $this->belongsTo(Grade::class, 'grade_id');
    }

    public function teacher()
    {
        return $this->belongsTo(Teacher::class, 'teacher_id');
    }

    public function files()
    {
        return $this->hasMany(AssignmentFile::class);
    }
}

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
        'user_id',
        'teacher_id',
        'gender',
        'phone',
        'subject',
        'dateofbirth',
        'cityofbirth',
        'address',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function grades()
    {
        return $this->belongsToMany(Grade::class,'teacher_grade');
    }

    public function assignments()
    {
        return $this->hasMany(Assignment::class,);
    }
}

app/Http/Controllers/AssignmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Grade;
use App\Models\Teacher;
use App\Models\Assignment;
use App\Models\AssignmentFile;
use App\Models\Student;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;

class AssignmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $teacher = Teacher::findOrFail(auth()->user()->teacher->id);
        return view('teacher.assignment.index', compact('teacher'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $grade = Grade::findOrFail($id);

        return view('teacher.assignment.create', compact('grade'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id)
    {
        $request->validate([
            'title'         => 'required|string|max:255|unique:assignments,title',
            'description'   => 'nullable|string|max:255',
        ]);

        $grade = Grade::findOrFail($id);

        $assignment = Assignment::create([
            'title'         => $request->title,
            'description'   => $request->description,
            'teacher_id'    => auth()->user()->teacher->id,
            'grade_id'      => $grade->id,
        ]);

        foreach ($grade->students as $student) {
            AssignmentFile::create([
                'assignment_id' => $assignment->id,
                'student_id'    => $student->id,
            ]);
        }

        return redirect()->route('assignment-manager.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // return view('teacher.assignment.edit', compact());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $assignment = Assignment::findOrFail($id);
        return view('teacher.assignment.show', compact('assignment'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $assignment = Assignment::findOrFail($id);
        foreach ($assignment->files as $AssignmentFile) {
            File::delete('assignment/' . $AssignmentFile->file);
            $AssignmentFile->delete();
        }
        $assignment->delete();

        return back()->with('success', 'Assignment deleted successfully');
    }


    // Student

    public function student()
    {
        $student = Student::findOrFail(auth()->user()->student->id);
        return view('student.assignment.index', compact('student'));
    }

    public function submit($id)
    {
        $AssignmentFile = AssignmentFile::findOrFail($id);
        return view('student.assignment.submit', compact('AssignmentFile'));
    }

    public function submitAssignment(Request $request, $id)
    {
        $request->validate([
            'note'      => 'nullable|string|max:255',
            'file'      => 'required|max:10000|mimes:pdf' //max 10Mb add mimes:doc,docx for extension type and must be pdf
        ]);

        $AssignmentFile = AssignmentFile::where([['assignment_id', $id], ['student_id', auth()->user()->student->id]])->firstOrFail();
        File::delete('assignment/' . $AssignmentFile->file);
        $filename       = auth()->user()->name . '-' . Assignment::findOrFail($id)->title . '.' . $request->file->getClientOriginalExtension();
        $request->file->move(public_path('assignment'), $filename);

        $AssignmentFile->update([
            'note'      => $request->note,
            'file'      => $filename
        ]);

        return redirect()->route('assignment.student');
    }

    public function downloadFile($filename)
    {
        return response()->download(public_path('assignment/' . $filename));
    }

    public function score($id, Request $request)
    {
        $request->validate([
            'score' => 'required|numeric|max:100'
        ]);
        AssignmentFile::findOrFail($id)->update([
            'score' => $request->score
        ]);
        return redirect()->back();
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Teacher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teacher::with('user')->latest()->paginate(10);
        
        return view('admin.teachers.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'              => 'required|string|max:255',
            'email'             => 'required|string|email|max:255|unique:users',
            'password'          => 'required|string|min:8',
            'subject'           => 'required|string|max:255',
            'teacher_id'        => 'nullable|numeric|digits_between:10,18',
            'gender'            => 'nullable|string',
            'phone'             => 'nullable|numeric|digits_between:10,15',
            'dateofbirth'       => 'nullable|date',
            'cityofbirth'       => 'nullable|string|max:255',
            'address'           => 'nullable|string|max:255',
        ]);

        $user = User::create([
            'name'      => $request->name,
            'email'     => $request->email,
            'password'  => Hash::make($request->password)
        ]);
        
        if ($request->hasFile('profile_picture')) {
            $profile = Str::slug($user->name).'-'.$user->id.'.'.$request->profile_picture->getClientOriginalExtension();
            $request->profile_picture->move(public_path('images/profile'), $profile);
        } else {
            $profile = 'avatar.png';
        }
        $user->update([
            'profile_picture' => $profile
        ]);

        $user->teacher()->create([
            'gender'            => $request->gender,
            'teacher_id'        => $request->teacher_id,
            'subject'           => $request->subject,
            'phone'             => $request->phone,
            'dateofbirth'       => $request->dateofbirth,
            'cityofbirth'       => $request->cityofbirth,
            'address'           => $request->address,
        ]);

        $user->assignRole('Teacher');

        return redirect()->route('teacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        return view('admin.teachers.show', compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        return view('admin.teachers.edit', compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Teacher $teacher)
    {
        $request->validate([
            'name'              => 'required|string|max:255',
            'email'             => 'required|string|email|max:255|unique:users,email,'.$teacher->user_id,
            'subject'           => 'required|string|max:255',
            'gender'            => 'nullable|string',
            'teacher_id'        => 'nullable|numeric',
            'phone'             => 'nullable|string|max:255',
            'dateofbirth'       => 'nullable|date',
            'cityofbirth'       => 'nullable|string|max:255',
            'address'           => 'nullable|string|max:255'
        ]);

        $user = User::findOrFail($teacher->user_id);

        if ($request->hasFile('profile_picture')) {
            $profile = Str::slug($user->name).'-'.$user->id.'.'.$request->profile_picture->getClientOriginalExtension();
            $request->profile_picture->move(public_path('images/profile'), $profile);
        } else {
            $profile = $user->profile_picture;
        }

        $user->update([
            'name'              => $request->name,
            'email'             => $request->email,
            'profile_picture'   => $profile
        ]);

        $user->teacher()->update([
            'gender'            => $request->gender,
            'teacher_id'        => $request->teacher_id,
            'subject'           => $request->subject,
            'phone'             => $request->phone,
            'dateofbirth'       => $request->dateofbirth,
            'cityofbirth'       => $request->cityofbirth,
            'address'           => $request->address
        ]);

        return redirect()->route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        $user = User::findOrFail($teacher->user_id);

        $user->teacher()->delete();
        
        $user->removeRole('Teacher');

        if ($user->delete()) {
            if($user->profile_picture != 'avatar.png') {
                $image_path = public_path() . '/images/profile/' . $user->profile_picture;
                if (is_file($image_path) && file_exists($image_path)) {
                    unlink($image_path);
                }
            }
        }

        return back();
    }
}

resources/views/teacher/assignment/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="roles">

        <div class="flex items-center justify-between mb-6">
            <div>
                <h2 class="text-gray-700 uppercase font-bold">Buat tugas untuk kelas {{ $grade->class_name }}</h2>
            </div>
            <div class="flex flex-wrap items-center">
                <a href="{{ route('assignment-manager.index') }}" class="bg-gray-200 text-gray-700 text-sm uppercase py-2 px-4 flex items-center rounded">
                    <svg class="w-3 h-3 fill-current" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="long-arrow-alt-left" class="svg-inline--fa fa-long-arrow-alt-left fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"></path></svg>
                    <span class="ml-2 text-xs font-semibold">Kembali</span>
                </a>
            </div>
        </div>
        
        <div class="table w-full mt-8 bg-white rounded">

            <form action="{{ route('assignment-manager.store-assignment',['id'=>$grade->id]) }}" method="post" class="w-full max-w-xl px-6 py-12">
                @csrf
                <div class="md:flex md:items-center mb-6">
                    <div class="md:w-1/3">
                        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
                            Judul
                        </label>
                    </div>
                    <div class="md:w-2/3">
                        <input name="title" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500" type="text" value="">
                        @error('title')
                            <p class="text-red-500 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                
                <div class="md:flex md:items-center mb-6">
                    <div class="md:w-1/3">
                        <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
                            Deskripsi
                        </label>
                    </div>
                    <div class="md:w-2/3">
                        <input name="description" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500" type="text" value="">
                        @error('description')
                            <p class="text-red-500 text-xs italic">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                {{-- @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li style="color: red">{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif --}}

                <div class="md:flex md:items-center">
                    <div class="md:w-1/3"></div>
                    <div class="md:w-2/3">
                        <button class="shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit">
                            Selesai
                        </button>
                    </div>
                </div>

            </form>        
        </div>
    </div>
@endsection

resources/views/teacher/assignment/index.blade.php
@extends('layouts.app')

@section('content')
    @foreach ($teacher->grades as $class)

    <div class="mt-8 rounded border-b-4 border-gray-300">
        <h1 class="text-xl text-gray-700 uppercase font-bold">Nama Kelas : {{ $class->class_name }}</h1>
        <a href="{{ route('assignment-manager.create-assignment',$class->id) }}" class="bg-gray-200 text-gray-700 text-sm uppercase py-2 px-4 flex items-center rounded">
            <svg class="w-3 h-3 fill-current" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="plus" class="svg-inline--fa fa-plus fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"></path></svg>
            <span class="ml-2 text-xs font-semibold">Assignment</span>
        </a>
        <div class="flex flex-wrap items-center uppercase text-sm font-semibold bg-gray-300 text-gray-600 rounded-tl rounded-tr">
            <div class="w-1/6 px-4 py-3">#</div>
            <div class="w-2/6 px-4 py-3">Judul</div>
            <div class="w-1/6 px-4 py-3">Deskripsi</div>
            <div class="w-2/6 px-4 py-3 text-right">Atur</div>
        </div>

        @php $index=1 @endphp

        @foreach ($class->assignments as $assignment)

            @if ( $assignment->teacher_id == $teacher->id )

            <div class="flex flex-wrap items-center text-gray-700 border-t-2 border-l-4 border-r-4 border-gray-300">
                <div class="w-1/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $index }}</div>
                <div class="w-2/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $assignment->title }}</div>
                <div class="w-1/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $assignment->description }}</div>
                <div class="w-2/6 flex items-center justify-end px-3">
                    <a href="{{ route('assignment-manager.show',$assignment->id) }}" class="ml-1 bg-gray-600 block p-1 border border-gray-600 rounded-sm" title="assign subject">
                        <svg class="h-3 w-3 fill-current text-gray-100" aria-hidden="true" focusable="false" data-prefix="far" data-icon="eye" class="svg-inline--fa fa-eye fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M288 144a110.94 110.94 0 0 0-31.24 5 55.4 55.4 0 0 1 7.24 27 56 56 0 0 1-56 56 55.4 55.4 0 0 1-27-7.24A111.71 111.71 0 1 0 288 144zm284.52 97.4C518.29 135.59 410.93 64 288 64S57.68 135.64 3.48 241.41a32.35 32.35 0 0 0 0 29.19C57.71 376.41 165.07 448 288 448s230.32-71.64 284.52-177.41a32.35 32.35 0 0 0 0-29.19zM288 400c-98.65 0-189.09-55-237.93-144C98.91 167 189.34 112 288 112s189.09 55 237.93 144C477.1 345 386.66 400 288 400z"></path></svg>
                    </a>
                    {{-- <a href="{{ route('assignment-manager.edit',$assignment->id) }}" class="ml-1">
                        <svg class="h-6 w-6 fill-current text-gray-600" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="pen-square" class="svg-inline--fa fa-pen-square fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M400 480H48c-26.5 0-48-21.5-48-48V80c0-26.5 21.5-48 48-48h352c26.5 0 48 21.5 48 48v352c0 26.5-21.5 48-48 48zM238.1 177.9L102.4 313.6l-6.3 57.1c-.8 7.6 5.6 14.1 13.3 13.3l57.1-6.3L302.2 242c2.3-2.3 2.3-6.1 0-8.5L246.7 178c-2.5-2.4-6.3-2.4-8.6-.1zM345 165.1L314.9 135c-9.4-9.4-24.6-9.4-33.9 0l-23.1 23.1c-2.3 2.3-2.3 6.1 0 8.5l55.5 55.5c2.3 2.3 6.1 2.3 8.5 0L345 199c9.3-9.3 9.3-24.5 0-33.9z"></path></svg>
                    </a> --}}
                    <form action="{{ route('assignment-manager.destroy',$assignment->id) }}" method="POST" class="inline-flex ml-1 delete">
                        @csrf
                        @method('DELETE')
                        <button type="submit" onclick="return confirm('Peringatan! File tugas yang telah dikumpulkan akan ikut dihapus.')" class="bg-gray-600 block p-1 border border-gray-600 rounded-sm">
                            <svg class="h-3 w-3 fill-current text-gray-100" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash" class="svg-inline--fa fa-trash fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16zM53.2 467a48 48 0 0 0 47.9 45h245.8a48 48 0 0 0 47.9-45L416 128H32z"></path></svg>
                        </button>
                    </form>
                </div>
            </div>

            @php $index+=1 @endphp

            @endif
        @endforeach

    </div>

    @endforeach

@endsection

resources/views/teacher/assignment/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="flex items-center justify-between mb-6">
        <div>
            <h2 class="text-gray-700 uppercase font-bold">{{ $assignment->title }}</h2>
        </div>
        <div class="flex flex-wrap items-center">
            <a href="{{ route('assignment-manager.index') }}" class="bg-gray-200 text-gray-700 text-sm uppercase py-2 px-4 flex items-center rounded">
                <svg class="w-3 h-3 fill-current" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="long-arrow-alt-left" class="svg-inline--fa fa-long-arrow-alt-left fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"></path></svg>
                <span class="ml-2 text-xs font-semibold">Kembali</span>
            </a>
        </div>
    </div>

    <div class="mt-8 rounded border-b-4 border-gray-300">
        <div class="flex flex-wrap items-center uppercase text-sm font-semibold bg-gray-300 text-gray-600 rounded-tl rounded-tr">
            <div class="w-1/6 px-4 py-3">#</div>
            <div class="w-1/6 px-4 py-3">Nama</div>
            <div class="w-1/6 px-4 py-3">Status</div>
            <div class="w-2/6 px-4 py-3">Catatan</div>
            <div class="w-1/6 px-4 py-3 text-right">Download</div>
        </div>

        @php $index=1 @endphp
        
        @foreach ($assignment->files as $assignment)

            <div class="flex flex-wrap items-center text-gray-700 border-t-2 border-l-4 border-r-4 border-gray-300">
                <div class="w-1/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $index }}</div>
                <div class="w-1/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $assignment->student->user->name }}</div>
                @if (empty($assignment->file))
                    <div class="w-1/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">Belum Mengumpulkan</div>
                @else
                    <form class="w-1/6 px-4 py-3 flex" method="POST" action="{{ route('assignment-manager.scoring',$assignment->id) }}">
                        @csrf
                        <div class=" text-sm font-semibold text-gray-600 tracking-tight md:w-1/3">
                            <label class="block md:text-right mb-1 md:mb-0 pr-4">
                                Nilai
                            </label>
                        </div>
                        <div class="md:w-2/3">
                            <input name="score" class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full  text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500" type="text" value="{{ $assignment->score }}">
                        </div>
                    </form>
                @endif
                <div class="w-2/6 px-4 py-3 text-sm font-semibold text-gray-600 tracking-tight">{{ $assignment->note }}</div>
                <div class="animate-bounce w-1/6 flex items-center justify-end px-3">
                    @if (!empty($assignment->file))
                        <a href="{{ route('assignment-manager.download',$assignment->file) }}" class="ml-1 block p-2">
                                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg>
                        </a>
                    @endif                       
                </div>
            </div>

            @php $index+=1 @endphp

        @endforeach

    </div>

@endsection